# AADD 2026 Adversarial Robustness Evaluation
# In order to run the AADD_2026_evaluation.py script, you must provide:
original_root: ../AADD-2026/AADD_2026_Test  

attack: ifgsm

save_attacked_dir: null

models_dir: weights/ 

save_json: experiments/results_ifgsm.json


# You can choose one or both of the classifiers at time of evaluation:
classifiers:                              
  - vit_b_16
  # - densenet121_dct


# Leave the settings below unchanged (the evaluation will be based on these, such reported on challenge Website: https://iplab.dmi.unict.it/mfs/acm-aadd-challenge-2026/):
dct_log_scale: true

weights:
  vit_b_16:    1.0
  densenet121_dct: 1.0

aggregate: sum  

device: auto  

alpha: 0.5 # weight for alpha*SSIM vs (1-alpha)*(1-LPIPS)
